/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicente
 */

import java.util.*;

public class MenuArtistasVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuArtistasVentana
     */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Artista> artistas;
    private final HashMap<String, Obra> obras;

    public MenuArtistasVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Artista> artistas, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.artistas = artistas;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuPrincipal = new javax.swing.JButton();
        BuscarObrasPorArtista = new javax.swing.JButton();
        MostrarArtistas = new javax.swing.JButton();
        MenuArtistas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuPrincipal.setText("Volver Al Menu Principal");
        VolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrincipalActionPerformed(evt);
            }
        });

        BuscarObrasPorArtista.setText("Buscar Obras por Artista");
        BuscarObrasPorArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarObrasPorArtistaActionPerformed(evt);
            }
        });

        MostrarArtistas.setText("Mostrar Artistas");
        MostrarArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArtistasActionPerformed(evt);
            }
        });

        MenuArtistas.setText("                   Menú Artistas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MenuArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MostrarArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarObrasPorArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(200, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(MenuArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(MostrarArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BuscarObrasPorArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(167, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrincipalActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuPrincipalActionPerformed

    private void BuscarObrasPorArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarObrasPorArtistaActionPerformed
        BuscarObrasArtistaVentana buscar = new BuscarObrasArtistaVentana(this, artistas, obras);
        buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarObrasPorArtistaActionPerformed

    private void MostrarArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArtistasActionPerformed
        MostrarArtistasVentana mostrar = new MostrarArtistasVentana(this, artistas);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarArtistasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarObrasPorArtista;
    private javax.swing.JLabel MenuArtistas;
    private javax.swing.JButton MostrarArtistas;
    private javax.swing.JButton VolverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
