
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicente Gamboa
 */
public class MenuObrasVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuObrasVentana
     */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Obra> obras;
    private final HashMap<String, Artista> artistas;

    public MenuObrasVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Obra> obras, HashMap<String, Artista> artistas) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.obras = obras;
        this.artistas = artistas;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuPrincipal = new javax.swing.JButton();
        BuscarObra = new javax.swing.JButton();
        MostrarObras = new javax.swing.JButton();
        MenuObras = new javax.swing.JLabel();
        RegistrarObra = new javax.swing.JButton();
        ModificarObra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuPrincipal.setText("Volver Al Menu Principal");
        VolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrincipalActionPerformed(evt);
            }
        });

        BuscarObra.setText("Buscar Obra");
        BuscarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarObraActionPerformed(evt);
            }
        });

        MostrarObras.setText("Mostrar Obras");
        MostrarObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarObrasActionPerformed(evt);
            }
        });

        MenuObras.setText("                   Menú Obras");

        RegistrarObra.setText("Registrar Obra");
        RegistrarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarObraActionPerformed(evt);
            }
        });

        ModificarObra.setText("Modificar Obra");
        ModificarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(MenuObras, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(MostrarObras, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(BuscarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(RegistrarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(ModificarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MenuObras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(MostrarObras, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(BuscarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(RegistrarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(ModificarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrincipalActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuPrincipalActionPerformed

    private void BuscarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarObraActionPerformed
        BuscarObraVentana buscar = new BuscarObraVentana(this, obras);
        buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarObraActionPerformed

    private void MostrarObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarObrasActionPerformed
        MostrarObrasVentana mostrar = new MostrarObrasVentana(this, obras);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarObrasActionPerformed

    private void RegistrarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarObraActionPerformed
        RegistrarObraVentana registrar = new RegistrarObraVentana(this, obras, artistas);
        registrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarObraActionPerformed

    private void ModificarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarObraActionPerformed
        // TODO add your handling code here:
        MenuModificarObraVentana mod= new MenuModificarObraVentana(this, obras, artistas);
        mod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModificarObraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarObra;
    private javax.swing.JLabel MenuObras;
    private javax.swing.JButton ModificarObra;
    private javax.swing.JButton MostrarObras;
    private javax.swing.JButton RegistrarObra;
    private javax.swing.JButton VolverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
