/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Netaxion
 */
public class MenuModificarObraVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuModificarObra
     */
    private Obra obraActual;
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Obra> obras;
    private final HashMap<String, Artista> artistas;

    public MenuModificarObraVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Obra> obras, HashMap<String, Artista> artistas) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.obras = obras;
        this.artistas = artistas;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
        this.obraActual = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscarIDButton = new javax.swing.JButton();
        IDObra = new javax.swing.JTextField();
        AnioNuevo = new javax.swing.JTextField();
        tituloNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        volverButton.setForeground(new java.awt.Color(153, 0, 0));
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        guardarButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarButton.setForeground(new java.awt.Color(0, 102, 102));
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Menú modificar obra");

        buscarIDButton.setText("Buscar ID de obra");
        buscarIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDButtonActionPerformed(evt);
            }
        });

        IDObra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IDObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDObraActionPerformed(evt);
            }
        });

        tituloNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloNuevoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìtulo de la obra");

        jLabel3.setText("Año de la obra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarIDButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(25, 25, 25))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnioNuevo)
                            .addComponent(tituloNuevo)
                            .addComponent(IDObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDObra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed

        ventanaAnterior.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_volverButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        //si no se ha buscado una obra, no hay nada que modificar
        if(obraActual == null){
            JOptionPane.showMessageDialog(this, "Primero debe buscar una Obra por su ID.");
            return;
        }

        //se valida que el título no esté vacío
        String nuevoTitulo = tituloNuevo.getText().trim();
        if(nuevoTitulo.isEmpty()){
            JOptionPane.showMessageDialog(this, "El título no puede estar vacío.");
            return;
        }

        //se valida que el año sea un número entero
        int nuevoAnio;
        try{
            nuevoAnio = Integer.parseInt(AnioNuevo.getText().trim());
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "El año debe ser un número entero.");
            return;
        }
        //se valida que el año no sea negativo
        if(nuevoAnio < 0){
            JOptionPane.showMessageDialog(this, "El año no puede ser negativo.");
            return;
        }

        //se aplican los cambios sobre la obra
        obraActual.setTitulo(nuevoTitulo);
        obraActual.setAnio(nuevoAnio);

        JOptionPane.showMessageDialog(this, "La obra fue modificada con éxito.");

    }//GEN-LAST:event_guardarButtonActionPerformed

    private void buscarIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDButtonActionPerformed
        // TODO add your handling code here:
        String id = IDObra.getText().trim();
        //se valida que el ID no esté vacío
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la Obra.");
            return;
        }
        //si la obra no está en el mapa, se retorna y no se muestra nada
        if(!obras.containsKey(id)){
            JOptionPane.showMessageDialog(this, "La obra no se encuentra en el sistema");
            obraActual = null;
            return;
        }
        //se guarda la obra encontrada y se muestran sus datos actuales en los campos
        obraActual = obras.get(id);
        tituloNuevo.setText(obraActual.getTitulo());
        AnioNuevo.setText("" + obraActual.getAnio());
    }//GEN-LAST:event_buscarIDButtonActionPerformed

    private void IDObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDObraActionPerformed

    private void tituloNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnioNuevo;
    private javax.swing.JTextField IDObra;
    private javax.swing.JButton buscarIDButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tituloNuevo;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
