/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vicente
 */

import java.util.*;
import javax.swing.table.DefaultTableModel;

public class RegistrarObraVentana extends javax.swing.JFrame {

    /** Creates new form RegistrarObraVentana */
    private HashMap<String, Obra> obras;
    private HashMap<String, Artista> artistas;
    
    public RegistrarObraVentana() {
        initComponents();
    }
    public RegistrarObraVentana(HashMap<String, Obra> obras, HashMap<String, Artista> artistas) {
        initComponents();
        this.obras = obras;
        this.artistas = artistas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuObras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TituloObra = new javax.swing.JLabel();
        IngresarTituloObra = new javax.swing.JTextField();
        NombreArtistaObra = new javax.swing.JLabel();
        IngresarArtistaObra = new javax.swing.JTextField();
        AnioCreacionObra = new javax.swing.JLabel();
        IngresarAnioObra = new javax.swing.JTextField();
        RegistrarObraBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuObras.setText("Menu Obras");
        VolverMenuObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuObrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrar Obra");

        TituloObra.setText("Título De La Obra:");

        NombreArtistaObra.setText("Nombre Artista:");

        AnioCreacionObra.setText("Año De Creación:");

        RegistrarObraBoton.setText("Registrar Obra");
        RegistrarObraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarObraBotonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(VolverMenuObras))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jLabel1)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(TituloObra)
                                    .add(NombreArtistaObra)))
                            .add(AnioCreacionObra))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(IngresarAnioObra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .add(IngresarTituloObra)
                            .add(IngresarArtistaObra))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .add(RegistrarObraBoton)
                .add(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(VolverMenuObras)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TituloObra)
                    .add(IngresarTituloObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NombreArtistaObra)
                    .add(IngresarArtistaObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra)
                    .add(IngresarAnioObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RegistrarObraBoton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuObrasActionPerformed
        MenuObrasVentana menu = new MenuObrasVentana(obras, artistas);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuObrasActionPerformed

    private void RegistrarObraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarObraBotonActionPerformed
        String titulo = IngresarTituloObra.getText();
        String id = IDManager.generarID(titulo);
        Random random = new Random();
        while (obras.containsKey(id)){
            int num = random.nextInt(1000);
            id = IDManager.generarID(titulo + "" + num);
        }

        String nombreArtista = IngresarArtistaObra.getText();
        int anio = Integer.parseInt(IngresarAnioObra.getText());
        
        Obra o = new Obra(id, titulo, null, "Disponible", anio);
        
        String nombreArtistaLower = nombreArtista.toLowerCase();
        Artista a;
        
        if (artistas.containsKey(nombreArtistaLower)) {
            // Como el artista ya existe, lo buscamos en el mapa
            a = artistas.get(nombreArtistaLower);
            a.anadirObra(o); // y añadimos la obra a su lista de obras asociada
        } else {
            // Como el artista no existe, lo creamos
            a = new Artista(nombreArtista, o);
            artistas.put(nombreArtistaLower, a); // y lo metemos al mapa global
        }
        
        o.setArtista(a);

        obras.put(id, o);
        javax.swing.JOptionPane.showMessageDialog(this, "Obra añadida correctamente", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RegistrarObraBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarObraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarObraVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCreacionObra;
    private javax.swing.JTextField IngresarAnioObra;
    private javax.swing.JTextField IngresarArtistaObra;
    private javax.swing.JTextField IngresarTituloObra;
    private javax.swing.JLabel NombreArtistaObra;
    private javax.swing.JButton RegistrarObraBoton;
    private javax.swing.JLabel TituloObra;
    private javax.swing.JButton VolverMenuObras;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
