
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicente
 */
public class MenuPrincipalVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalVentana
     */
    HashMap<String, Obra> obras;
    HashMap<String, Artista> artistas;
    HashMap<String, Exposicion> exposiciones;
    ArrayList<Venta> ventas;
    HashMap<String, Cliente> clientes;
    ArrayList<Prestamo> prestamos;
    ArrayList<Subasta> subastas;
    
    public MenuPrincipalVentana() {
        initComponents();
    }
    public MenuPrincipalVentana(HashMap<String, Obra> obras, HashMap<String, Artista> artistas, 
                       HashMap<String, Exposicion> exposiciones, ArrayList<Venta> ventas, 
                       HashMap<String, Cliente> clientes, ArrayList<Prestamo> prestamos, ArrayList<Subasta> subastas){
        initComponents();
        this.obras = obras;
        this.artistas = artistas;
        this.exposiciones = exposiciones;
        this.ventas = ventas;
        this.clientes = clientes;
        this.prestamos = prestamos;
        this.subastas = subastas;
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuObras = new javax.swing.JButton();
        MenuArtistas = new javax.swing.JButton();
        ShaolinArtManager = new javax.swing.JLabel();
        MenuVentas = new javax.swing.JButton();
        MenuPrestamos = new javax.swing.JButton();
        MenuExposiciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        MenuObras.setText("Menu Obras");
        MenuObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuObrasActionPerformed(evt);
            }
        });

        MenuArtistas.setText("Menu Artistas");
        MenuArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArtistasActionPerformed(evt);
            }
        });

        ShaolinArtManager.setText("                                Shaolin Art Manager");

        MenuVentas.setText("Menu Ventas");
        MenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVentasActionPerformed(evt);
            }
        });

        MenuPrestamos.setText("Menu Prestamos");
        MenuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrestamosActionPerformed(evt);
            }
        });

        MenuExposiciones.setText("Menu Exposiciones");
        MenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExposicionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShaolinArtManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuArtistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ShaolinArtManager, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(MenuObras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuArtistas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuObrasActionPerformed
        // TODO add your handling code here:
        MenuObrasVentana v1 = new MenuObrasVentana(obras, artistas);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuObrasActionPerformed

    private void MenuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrestamosActionPerformed
        MenuPrestamosVentana v4 = new MenuPrestamosVentana();
        v4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuPrestamosActionPerformed

    private void MenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExposicionesActionPerformed
        MenuExposicionesVentana v5 = new MenuExposicionesVentana();
        v5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuExposicionesActionPerformed

    private void MenuArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArtistasActionPerformed
        MenuArtistasVentana v2 = new MenuArtistasVentana(artistas);
        v2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuArtistasActionPerformed

    private void MenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVentasActionPerformed
        MenuVentasVentana v3 = new MenuVentasVentana(ventas, obras, clientes, subastas);
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuArtistas;
    private javax.swing.JButton MenuExposiciones;
    private javax.swing.JButton MenuObras;
    private javax.swing.JButton MenuPrestamos;
    private javax.swing.JButton MenuVentas;
    private javax.swing.JLabel ShaolinArtManager;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
