/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class BuscarVentaVentana extends javax.swing.JFrame {

    /** Creates new form BuscarVentaVentana */
    private ArrayList<Venta> ventas;
    private HashMap<String, Obra> obras;


    public BuscarVentaVentana() {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
    }
    public BuscarVentaVentana(ArrayList<Venta> ventas, HashMap<String, Obra> obras){
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.ventas = ventas;
        this.obras = obras;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        BuscarObraPorID = new javax.swing.JButton();
        VolverMenuVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Buscar Venta");

        jLabel1.setText("ID Obra:");

        BuscarObraPorID.setText("Buscar Venta");
        BuscarObraPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarObraPorIDActionPerformed(evt);
            }
        });

        VolverMenuVentas.setText("Menu Ventas");
        VolverMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuVentasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addComponent(VolverMenuVentas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarObraPorID))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(VolverMenuVentas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarObraPorID))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarObraPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarObraPorIDActionPerformed
        //si no hay ventas, se da un aviso y se retorna
        if (ventas.size() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ventas registradas.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //se busca la obra vendida. De no existir, se da un aviso y se retorna
        String idObra = IngresarIDObra.getText().trim();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //al obtener la obra, si no esta vendida se da un aviso y se retorna
        Obra o = obras.get(idObra);
        if(!(o.getEstado()).equalsIgnoreCase("VENDIDA")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra '" + o.getTitulo() + "' no ha sido vendida.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //como se sabe que esta vendida, se busca y se muestra en la tabla
        String[] columnas = {"RUT", "OBRA VENDIDA", "ARTISTA", "PRECIO $", "FECHA DE VENTA"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        Venta auxV;
        for(int i = 0; i < ventas.size() ; i++){
            auxV = (Venta) ventas.get(i);
            if (auxV.getObra() == o){
                String rut = "Ninguno";
                if (auxV.getCliente() != null){
                    rut = (auxV.getCliente()).getRut();
                }
                Object[] fila = {rut, o.getTitulo(), (o.getArtista()).getNombre(), auxV.getPrecio(), auxV.getFechaVenta()};
                modeloTabla.addRow(fila);
                jTable1.setModel(modeloTabla);
                return;
            }
        }
        //si por alguna razón no se encontró, se da aviso
        jTable1.setModel(modeloTabla);
        javax.swing.JOptionPane.showMessageDialog(this, "'" + o.getTitulo() + "' sale vendida pero no se encontró en la lista de ventas.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BuscarObraPorIDActionPerformed

    private void VolverMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuVentasActionPerformed
        MenuVentasVentana menu = new MenuVentasVentana(Datos.ventas, Datos.obras, Datos.clientes, Datos.subastas);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVentaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVentaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVentaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVentaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVentaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JButton BuscarObraPorID;
    private javax.swing.JButton VolverMenuVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
