
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
public class EliminarVentaVentana extends javax.swing.JFrame {

    /** Creates new form EliminarVentaVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final ArrayList<Venta> ventas;
    private final HashMap<String, Obra> obras;

    public EliminarVentaVentana(javax.swing.JFrame ventanaAnterior, ArrayList<Venta> ventas, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.ventas = ventas;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IngreseIDObra = new javax.swing.JTextField();
        EliminarVenta = new javax.swing.JButton();
        VolverMenuVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Obra:");

        IngreseIDObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreseIDObraActionPerformed(evt);
            }
        });

        EliminarVenta.setText("Eliminar Venta");
        EliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVentaActionPerformed(evt);
            }
        });

        VolverMenuVentas.setText("Menu Ventas");
        VolverMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuVentasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(IngreseIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(EliminarVenta)
                                .add(122, 122, 122))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(VolverMenuVentas)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(VolverMenuVentas)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngreseIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(EliminarVenta)
                .add(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseIDObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseIDObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseIDObraActionPerformed

    private void VolverMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuVentasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuVentasActionPerformed

    private void EliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVentaActionPerformed
        //si no hay ventas, se da un aviso y se retorna al menu
        if (ventas.size() == 0){ 
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //se busca la obra vendida. De no existir, se da un aviso y se retorna al menu
        String id = IngreseIDObra.getText();
        if(!obras.containsKey(id)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(id.toLowerCase());
        if(!(o.getEstado()).equals("VENDIDA")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra NO ha sido vendida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //como se sabe que esta vendida, se busca, se elimina y se da un aviso de ello
        Venta auxV; 
        for (int i = 0 ; i < ventas.size() ; i++ ){
            auxV = (Venta) ventas.get(i);
            if (auxV.getObra() == o){
                Cliente cl = auxV.getCliente(); //se obtiene el cliente de la venta 
                if (!cl.elimObComprada(o)){ //se elimina la obra de la lista de obras compradas del cliente 
                    javax.swing.JOptionPane.showMessageDialog(this, "El cliente no es dueño de la Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                } 
                ventas.remove(auxV); //se elimina la venta de la lista de ventas 
                javax.swing.JOptionPane.showMessageDialog(this, "Venta eliminada con éxito", "EXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                o.setEstado("Disponible");
                return;
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la venta", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_EliminarVentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVenta;
    private javax.swing.JTextField IngreseIDObra;
    private javax.swing.JButton VolverMenuVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
