
/**
 * @archivo: RegistrarVentaVentana.java
 * @Proyecto: Shaolin Art Manager 
 * @Descripción: Método para registrar ventas por ventana
 * @author Vicente Gamboa
 * @Lenguaje: Java
*/

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.*;


public class RegistrarVentaVentana extends javax.swing.JFrame {

    /** Creates new form RegistrarVentaVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final ArrayList<Venta> ventas;
    private final HashMap<String, Obra> obras;
    private final HashMap<String, Cliente> clientes;

    public RegistrarVentaVentana(javax.swing.JFrame ventanaAnterior, ArrayList<Venta> ventas, HashMap<String, Obra> obras, HashMap<String, Cliente> clientes) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.ventas = ventas;
        this.obras = obras;
        this.clientes = clientes;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresarFechaVenta = new javax.swing.JTextField();
        AnioCreacionObra = new javax.swing.JLabel();
        IngresarRutCliente = new javax.swing.JTextField();
        RegistrarVentaBoton = new javax.swing.JButton();
        VolverMenuVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDObra = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        NombreArtistaObra = new javax.swing.JLabel();
        AnioCreacionObra1 = new javax.swing.JLabel();
        IngresarMontoVenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnioCreacionObra.setText("Rut Cliente:");

        RegistrarVentaBoton.setText("Registrar Venta");
        RegistrarVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVentaBotonActionPerformed(evt);
            }
        });

        VolverMenuVentas.setText("Menu Ventas");
        VolverMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuVentasActionPerformed(evt);
            }
        });

        jLabel1.setText("Generar Venta");

        IDObra.setText("ID de la Obra:");

        NombreArtistaObra.setText("Fecha Venta:");

        AnioCreacionObra1.setText("Monto Venta:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(VolverMenuVentas))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel1)
                                    .add(IDObra)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra1)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, NombreArtistaObra))))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(IngresarMontoVenta)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarRutCliente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarIDObra)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarFechaVenta))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 154, Short.MAX_VALUE)
                .add(RegistrarVentaBoton)
                .add(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(VolverMenuVentas)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IDObra)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NombreArtistaObra)
                    .add(IngresarFechaVenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra)
                    .add(IngresarRutCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra1)
                    .add(IngresarMontoVenta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RegistrarVentaBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se valida el formato del rut ingresado: 7 u 8 dígitos, sin guion ni dígito verificador
    private void validarFormatoRut(String rut) throws FormatoRutException {
        if (rut.length() < 7 || rut.length() > 8) {
            throw new FormatoRutException();
        }
        //se verifica que el rut contenga solo números
        for (int i = 0; i < rut.length(); i++) {
            if (!Character.isDigit(rut.charAt(i))) {
                throw new FormatoRutException();
            }
        }
    }
    
    //Se calcula el dígito verificador del rut
    private char calcularDigitoVerificador(String rut) {
        int suma = 0;
        int multiplicador = 2;
        int rutInt = Integer.parseInt(rut);
        // Recorrer los dígitos del RUT de derecha a izquierda
        while (rutInt > 0) {
            int digito = rutInt % 10;
            suma += digito * multiplicador;
            rutInt /= 10;
            
            multiplicador++;
            if (multiplicador > 7) {
                multiplicador = 2; // Reiniciar el ciclo de factores (2 al 7)
            }
        }
        
        // Aplicar la fórmula del módulo 11
        int resto = suma % 11;
        int resultado = 11 - resto;
        
        // Casos especiales
        if (resultado == 11) {
            return '0';
        } else if (resultado == 10) {
            return 'K';
        }
        return Character.forDigit(resultado, 10);
    }
    
    
    private void RegistrarVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVentaBotonActionPerformed
         String idObra = IngresarIDObra.getText();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(idObra.toLowerCase());
        if(!(o.getEstado()).equals("Disponible")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra no está disponible", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String rut = IngresarRutCliente.getText().trim();

        //se valida el formato del rut y se le agrega el dígito verificador, igual que en consola
        try {
            validarFormatoRut(rut);
        } catch (FormatoRutException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage() + ". Ingrese 7 u 8 dígitos, sin guion ni dígito verificador", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        rut = rut + calcularDigitoVerificador(rut);
        
        LocalDate fecha = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada = IngresarFechaVenta.getText(); 
        try { 
            fecha = LocalDate.parse(entrada); 
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        int monto = -1;
        try {
            monto = Integer.parseInt(IngresarMontoVenta.getText().trim());
            if (monto < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un monto válido", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un monto válido", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        Cliente c;
        if(!clientes.containsKey(rut)){
            c = new Cliente(rut);
            clientes.put(rut, c);
        }
        else{
            c = clientes.get(rut);
        }
        Venta n = new Venta(fecha, c, o, monto);
        if(n.registrar()){
            javax.swing.JOptionPane.showMessageDialog(this, "Venta registrada correctamente", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR al registrar la compra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        ventas.add(n);
    }//GEN-LAST:event_RegistrarVentaBotonActionPerformed

    private void VolverMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuVentasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuVentasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCreacionObra;
    private javax.swing.JLabel AnioCreacionObra1;
    private javax.swing.JLabel IDObra;
    private javax.swing.JTextField IngresarFechaVenta;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JTextField IngresarMontoVenta;
    private javax.swing.JTextField IngresarRutCliente;
    private javax.swing.JLabel NombreArtistaObra;
    private javax.swing.JButton RegistrarVentaBoton;
    private javax.swing.JButton VolverMenuVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
