
import javax.swing.table.DefaultTableModel;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alexia Gallardo
 */
public class BuscarPrestamosVentana extends javax.swing.JFrame {

    /** Creates new form BuscarPrestamosVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final ArrayList<Prestamo> prestamos;
    private final HashMap<String, Obra> obras;

    public BuscarPrestamosVentana(javax.swing.JFrame ventanaAnterior, ArrayList<Prestamo> prestamos, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.prestamos = prestamos;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IngresarIDObraPrestada = new javax.swing.JTextField();
        BuscarPrestamoPorID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VolverMenuPrestamos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Obra Prestada:");

        BuscarPrestamoPorID.setText("Buscar Préstamo");
        BuscarPrestamoPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPrestamoPorIDActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        VolverMenuPrestamos.setText("Menu Préstamos");
        VolverMenuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrestamosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(IngresarIDObraPrestada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(BuscarPrestamoPorID)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(VolverMenuPrestamos))
                    .add(layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngresarIDObraPrestada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BuscarPrestamoPorID)
                    .add(VolverMenuPrestamos))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPrestamoPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPrestamoPorIDActionPerformed
        //si no hay prestamos, se da un aviso y se retorna al menu
        if (prestamos.size() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "No hay préstamos registrados.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //se busca la obra prestada. De no existir, se da un aviso y se retorna al menu
        String id = IngresarIDObraPrestada.getText();
        if(!obras.containsKey(id)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra oPres = obras.get(id.toLowerCase());
        if(!(oPres.getEstado()).equals("PRESTADA")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra NO ha sido prestada", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //como se sabe que esta prestada, se buscan los préstamos y se muestran
        String[] columnas = {"ID", "RUT", "OBRA PRESTADA", "ARTISTA", "FECHA DE INICIO", "FECHA DE RETORNO"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        for(int i = 0; i < prestamos.size() ; i++){
            Prestamo p = (Prestamo) prestamos.get(i);
            Obra o = (Obra) p.getObra();
            //si la obra prestada es igual a la obra dentro de la lista de obras prestadas, se muestra
            if (oPres.equals(o)){
                Object[] fila = { p.getId(), (p.getCliente()).getRut(), o.getTitulo() , (o.getArtista()).getNombre(), p.getFechaInicio(), p.getFechaRetorno()};
                modeloTabla.addRow(fila);
            }
        }
        jTable1.setModel(modeloTabla);        
    }//GEN-LAST:event_BuscarPrestamoPorIDActionPerformed

    private void VolverMenuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrestamosActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuPrestamosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPrestamoPorID;
    private javax.swing.JTextField IngresarIDObraPrestada;
    private javax.swing.JButton VolverMenuPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
