
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alexia Gallardo
 */
public class EliminarPrestamoVentana extends javax.swing.JFrame {

    /** Creates new form EliminarPrestamoVentana */
    private ArrayList<Prestamo> prestamos; 
    private HashMap<String, Obra> obras;
            
    public EliminarPrestamoVentana() {
        initComponents();
    }
    
    public EliminarPrestamoVentana(ArrayList<Prestamo> prestamos, HashMap<String, Obra> obras) {
        initComponents();
        this.prestamos= prestamos;
        this.obras= obras;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IngreseIDObra = new javax.swing.JTextField();
        EliminarPrestamo = new javax.swing.JButton();
        VolverMenuPrestamo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Obra:");

        IngreseIDObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreseIDObraActionPerformed(evt);
            }
        });

        EliminarPrestamo.setText("Eliminar Préstamo");
        EliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPrestamoActionPerformed(evt);
            }
        });

        VolverMenuPrestamo.setText("Menu Préstamos");
        VolverMenuPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrestamoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(IngreseIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 204, Short.MAX_VALUE)
                        .add(VolverMenuPrestamo)
                        .addContainerGap())))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(EliminarPrestamo)
                .add(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(VolverMenuPrestamo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngreseIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(EliminarPrestamo)
                .add(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreseIDObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreseIDObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreseIDObraActionPerformed

    private void EliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPrestamoActionPerformed
        //si no hay prestamos, se da un aviso y se retorna al menu
        if (prestamos.size() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "No hay préstamos registrados.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        //se busca la obra prestada. De no existir, se da un aviso y se retorna al menu
        String id = IngreseIDObra.getText();
        if(!obras.containsKey(id)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(id.toLowerCase());
        if(!(o.getEstado()).equals("PRESTADA")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra NO ha sido prestada", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //como se sabe que esta prestada, se busca, se elimina y se da un aviso de ello
        Prestamo auxP;
        for (int i = 0 ; i < prestamos.size() ; i++ ){
            auxP = (Prestamo) prestamos.get(i);
            if (auxP.getObra() == o){
                Cliente cl = auxP.getCliente(); //se obtiene el cliente del préstamo
                if (!cl.elimObComprada(o)){ //se elimina la obra de la lista de obras prestadas del cliente
                    javax.swing.JOptionPane.showMessageDialog(this, "El cliente no ha pedido prestada la obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                prestamos.remove(auxP); //se elimina el prestamo de la lista de prestamos
                javax.swing.JOptionPane.showMessageDialog(this, "Préstamo eliminado con éxito", "EXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                o.setEstado("Disponible");
                return;
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el préstamo", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_EliminarPrestamoActionPerformed

    private void VolverMenuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrestamoActionPerformed
        MenuPrestamosVentana menu = new MenuPrestamosVentana(); //SE LLAMA SIN PARÁMETROS YA QUE NO SE TIENEN TODOS 
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarPrestamoVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarPrestamo;
    private javax.swing.JTextField IngreseIDObra;
    private javax.swing.JButton VolverMenuPrestamo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
