import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alexia Gallardo
 */
public class RegistrarPrestamoVentana extends javax.swing.JFrame {

    /** Creates new form RegistrarPrestamoVentana */
    private ArrayList<Prestamo> prestamos;
    private HashMap<String, Obra> obras; 
    private HashMap<String, Cliente> clientes;
    
    public RegistrarPrestamoVentana() {
        initComponents();
    }
    
    public RegistrarPrestamoVentana(ArrayList<Prestamo> prestamos, HashMap<String, Cliente> clientes, HashMap<String, Obra> obras) {
        initComponents();
        this.prestamos = prestamos;
        this.obras = obras;
        this.clientes = clientes;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresarFechaTermino = new javax.swing.JTextField();
        IngresarRutCliente = new javax.swing.JTextField();
        AnioCreacionObra = new javax.swing.JLabel();
        IngresarFechaInicio = new javax.swing.JTextField();
        RegistrarPrestamoBoton = new javax.swing.JButton();
        VolverMenuPrestamos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDObra = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        NombreArtistaObra = new javax.swing.JLabel();
        AnioCreacionObra1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnioCreacionObra.setText("Fecha de INICIO préstamo:");

        RegistrarPrestamoBoton.setText("Registrar Préstamo");
        RegistrarPrestamoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPrestamoBotonActionPerformed(evt);
            }
        });

        VolverMenuPrestamos.setText("Menu Préstamos");
        VolverMenuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrestamosActionPerformed(evt);
            }
        });

        jLabel1.setText("Generar Préstamo");

        IDObra.setText("ID de la Obra:");

        NombreArtistaObra.setText("Rut Cliente:");

        AnioCreacionObra1.setText("Fecha TÉRMINO préstamo:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(VolverMenuPrestamos))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel1))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra1)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, NombreArtistaObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, IDObra))))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(IngresarFechaTermino)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarFechaInicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarIDObra)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarRutCliente))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 172, Short.MAX_VALUE)
                .add(RegistrarPrestamoBoton)
                .add(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(VolverMenuPrestamos)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IDObra)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NombreArtistaObra)
                    .add(IngresarRutCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra)
                    .add(IngresarFechaInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra1)
                    .add(IngresarFechaTermino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RegistrarPrestamoBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPrestamoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPrestamoBotonActionPerformed
        String idObra = IngresarIDObra.getText().trim();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(idObra.toLowerCase());
        if(!(o.getEstado()).equals("Disponible")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra ya ha sido prestada", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rut = IngresarRutCliente.getText().trim();
        
        // Si el usuario presiona 0 y enter, se termina el ciclo y se devuelve al menú para no quedar en loop infinito
        if (rut.equals("0")) {
            MenuPrestamosVentana menu = new MenuPrestamosVentana(prestamos, obras, clientes);
            menu.setVisible(true);
            this.setVisible(false);
        }

        if (rut.trim().isEmpty() || rut.trim().length() < 8 || rut.trim().length() > 9) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un RUT válido", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate fechaI = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada = IngresarFechaInicio.getText();
        try {
            fechaI = LocalDate.parse(entrada);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        LocalDate fechaT = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada2 = IngresarFechaTermino.getText();
        try {
            fechaT = LocalDate.parse(entrada2);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        //CREAR CLIENTE        
        Cliente c;
        if(!clientes.containsKey(rut)){
            c = new Cliente(rut);
            clientes.put(rut, c);
        }
        else{
            c = clientes.get(rut);
        }
        // SE GUARDA EL PRESTAMO 
        Prestamo n = new Prestamo(idObra, c, o, fechaI, fechaT);
        if(n.registrar()){
            javax.swing.JOptionPane.showMessageDialog(this, "Préstamo registrado correctamente", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR al registrar el préstamo", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        prestamos.add(n);
    }//GEN-LAST:event_RegistrarPrestamoBotonActionPerformed

    private void VolverMenuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrestamosActionPerformed
        MenuPrestamosVentana menu = new MenuPrestamosVentana(prestamos, obras, clientes);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPrestamoVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCreacionObra;
    private javax.swing.JLabel AnioCreacionObra1;
    private javax.swing.JLabel IDObra;
    private javax.swing.JTextField IngresarFechaInicio;
    private javax.swing.JTextField IngresarFechaTermino;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JTextField IngresarRutCliente;
    private javax.swing.JLabel NombreArtistaObra;
    private javax.swing.JButton RegistrarPrestamoBoton;
    private javax.swing.JButton VolverMenuPrestamos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
