/**
 * @archivo: RegistrarPrestamosVentana.java
 * @Proyecto: Shaolin Art Manager 
 * @Descripción: Método para registrar un préstamo por ventana
 * @author Alexia Gallardo
 * @Lenguaje: Java
*/

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.*;

public class RegistrarPrestamoVentana extends javax.swing.JFrame {

    /** Creates new form RegistrarPrestamoVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final ArrayList<Prestamo> prestamos;
    private final HashMap<String, Cliente> clientes;
    private final HashMap<String, Obra> obras;

    public RegistrarPrestamoVentana(javax.swing.JFrame ventanaAnterior, ArrayList<Prestamo> prestamos, HashMap<String, Cliente> clientes, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.prestamos = prestamos;
        this.clientes = clientes;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresarFechaTermino = new javax.swing.JTextField();
        IngresarRutCliente = new javax.swing.JTextField();
        AnioCreacionObra = new javax.swing.JLabel();
        IngresarFechaInicio = new javax.swing.JTextField();
        RegistrarPrestamoBoton = new javax.swing.JButton();
        VolverMenuPrestamos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDObra = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        NombreArtistaObra = new javax.swing.JLabel();
        AnioCreacionObra1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnioCreacionObra.setText("Fecha de INICIO préstamo:");

        RegistrarPrestamoBoton.setText("Registrar Préstamo");
        RegistrarPrestamoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPrestamoBotonActionPerformed(evt);
            }
        });

        VolverMenuPrestamos.setText("Menu Préstamos");
        VolverMenuPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrestamosActionPerformed(evt);
            }
        });

        jLabel1.setText("Generar Préstamo");

        IDObra.setText("ID de la Obra:");

        NombreArtistaObra.setText("Rut Cliente:");

        AnioCreacionObra1.setText("Fecha TÉRMINO préstamo:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(VolverMenuPrestamos))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel1))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra1)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, NombreArtistaObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, IDObra))))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(IngresarFechaTermino)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarFechaInicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarIDObra)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarRutCliente))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 172, Short.MAX_VALUE)
                .add(RegistrarPrestamoBoton)
                .add(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(VolverMenuPrestamos)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IDObra)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NombreArtistaObra)
                    .add(IngresarRutCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra)
                    .add(IngresarFechaInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(AnioCreacionObra1)
                    .add(IngresarFechaTermino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RegistrarPrestamoBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Se valida el formato del rut ingresado: 7 u 8 dígitos, sin guion ni dígito verificador
    private void validarFormatoRut(String rut) throws FormatoRutException {
        if (rut.length() < 7 || rut.length() > 8) {
            throw new FormatoRutException();
        }
        //se verifica que el rut contenga solo números
        for (int i = 0; i < rut.length(); i++) {
            if (!Character.isDigit(rut.charAt(i))) {
                throw new FormatoRutException();
            }
        }
    }
    
    //Se calcula el dígito verificador del rut
    private char calcularDigitoVerificador(String rut) {
        int suma = 0;
        int multiplicador = 2;
        int rutInt = Integer.parseInt(rut);
        // Recorrer los dígitos del RUT de derecha a izquierda
        while (rutInt > 0) {
            int digito = rutInt % 10;
            suma += digito * multiplicador;
            rutInt /= 10;
            
            multiplicador++;
            if (multiplicador > 7) {
                multiplicador = 2; // Reiniciar el ciclo de factores (2 al 7)
            }
        }
        
        // Aplicar la fórmula del módulo 11
        int resto = suma % 11;
        int resultado = 11 - resto;
        
        // Casos especiales
        if (resultado == 11) {
            return '0';
        } else if (resultado == 10) {
            return 'K';
        }
        return Character.forDigit(resultado, 10);
    }
    
    
    
    private void RegistrarPrestamoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPrestamoBotonActionPerformed
        String idObra = IngresarIDObra.getText().trim();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(idObra.toLowerCase());
        if(!(o.getEstado()).equals("Disponible")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra no está disponible", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rut = IngresarRutCliente.getText().trim();

        //se valida el formato del rut y se le agrega el dígito verificador, igual que en consola
        try {
            validarFormatoRut(rut);
        } catch (FormatoRutException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage() + ". Ingrese 7 u 8 dígitos, sin guion ni dígito verificador", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        rut = rut + calcularDigitoVerificador(rut);

        LocalDate fechaI = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada = IngresarFechaInicio.getText();
        try {
            fechaI = LocalDate.parse(entrada);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        LocalDate fechaT = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada2 = IngresarFechaTermino.getText();
        try {
            fechaT = LocalDate.parse(entrada2);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        //CREAR CLIENTE        
        Cliente c;
        if(!clientes.containsKey(rut)){
            c = new Cliente(rut);
            clientes.put(rut, c);
        }
        else{
            c = clientes.get(rut);
        }
        // SE GUARDA EL PRESTAMO 
        Prestamo n = new Prestamo(idObra, c, o, fechaI, fechaT);
        if(n.registrar()){
            javax.swing.JOptionPane.showMessageDialog(this, "Préstamo registrado correctamente", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR al registrar el préstamo", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        prestamos.add(n);
    
    }//GEN-LAST:event_RegistrarPrestamoBotonActionPerformed

    private void VolverMenuPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrestamosActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuPrestamosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCreacionObra;
    private javax.swing.JLabel AnioCreacionObra1;
    private javax.swing.JLabel IDObra;
    private javax.swing.JTextField IngresarFechaInicio;
    private javax.swing.JTextField IngresarFechaTermino;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JTextField IngresarRutCliente;
    private javax.swing.JLabel NombreArtistaObra;
    private javax.swing.JButton RegistrarPrestamoBoton;
    private javax.swing.JButton VolverMenuPrestamos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
