/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */

import java.util.*;
import javax.swing.table.DefaultTableModel;

public class AñadirObraExposicionVentana extends javax.swing.JFrame {
    /** Creates new form AñadirObraExposicionVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Exposicion> exposiciones;
    private final HashMap<String, Obra> obras;

    public AñadirObraExposicionVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.exposiciones = exposiciones;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VolverMenuExposiciones = new javax.swing.JButton();
        IngresarIDExposicion = new javax.swing.JTextField();
        IngresarIDObra = new javax.swing.JTextField();
        AnadirObraBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        VolverMenuExposiciones.setText("Menu Exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        IngresarIDObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarIDObraActionPerformed(evt);
            }
        });

        AnadirObraBoton.setText("Añadir Obra");
        AnadirObraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirObraBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID de la exposicion:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID de la obra:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, VolverMenuExposiciones)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(AnadirObraBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(VolverMenuExposiciones)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(AnadirObraBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se obtiene el texto de un campo, validando que no esté vacío
    private String obtenerTextoIngresado(javax.swing.JTextField campo) throws EmptyEntryException {
        String texto = campo.getText().trim();
        if(texto.isEmpty()){
            throw new EmptyEntryException();
        }
        return texto;
    }
    
    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    private void AnadirObraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirObraBotonActionPerformed
        // TODO add your handling code here:
        try{
            String idExpo = obtenerTextoIngresado(IngresarIDExposicion);
            String idObra = obtenerTextoIngresado(IngresarIDObra);

            //se busca la exposición
            if(!exposiciones.containsKey(idExpo)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Exposicion e = exposiciones.get(idExpo);

            //se busca la obra
            if(!obras.containsKey(idObra)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Obra o = obras.get(idObra);

            //se verifica el estado de la obra
            String estado = o.getEstado();
            if(!estado.equalsIgnoreCase("DISPONIBLE")){
                javax.swing.JOptionPane.showMessageDialog(this, "La obra '" + o.getTitulo() + "' no está disponible para exponerse (estado: " + estado + ")", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            //si la obra ya estaba en la exposición, anadirObra devuelve false
            if(!e.anadirObra(o)){
                javax.swing.JOptionPane.showMessageDialog(this, "La obra ya se encuentra en esta exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Obra añadida correctamente", "ÉXITO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //se actualiza la tabla con las obras de la exposición
            ArrayList<String> idObras = e.getIdsObras();
            String[] columnas = {"ID", "TITULO", "ARTISTA", "ESTADO", "AÑO"};
            DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
            for(int i = 0; i < idObras.size(); i++){
                Obra obra = obras.get(idObras.get(i));
                Object[] fila = {obra.getId(), obra.getTitulo(), (obra.getArtista()).getNombre(), obra.getEstado(), obra.getAnio()};
                modeloTabla.addRow(fila);
            }
            jTable1.setModel(modeloTabla);
            

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el ID de la Exposición y el ID de la Obra", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AnadirObraBotonActionPerformed

    private void IngresarIDObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarIDObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarIDObraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirObraBoton;
    private javax.swing.JTextField IngresarIDExposicion;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
