
import java.util.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
public class BuscarExposicionVentana extends javax.swing.JFrame {

    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Exposicion> exposiciones;
    private final HashMap<String, Obra> obras;

    public BuscarExposicionVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.exposiciones = exposiciones;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuExposiciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IngresarIDExposicion = new javax.swing.JTextField();
        BuscarExposicionPorID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DatosExposicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuExposiciones.setText("Menu Exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        BuscarExposicionPorID.setText("Buscar Exposiciones");
        BuscarExposicionPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarExposicionPorIDActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DatosExposicion.setText("Exposicion");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(BuscarExposicionPorID)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(VolverMenuExposiciones))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 452, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(DatosExposicion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BuscarExposicionPorID)
                    .add(VolverMenuExposiciones))
                .add(9, 9, 9)
                .add(DatosExposicion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String obtenerIdIngresado() throws EmptyEntryException {
        String id = IngresarIDExposicion.getText().trim();
        if(id.isEmpty()){
            throw new EmptyEntryException();
        }
        return id;
    }
    
    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    private void BuscarExposicionPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarExposicionPorIDActionPerformed
        try{
            //se obtiene el ID validado
            String id = obtenerIdIngresado();

            //si la exposición no está en el mapa, se avisa y no se muestra nada
            if(!exposiciones.containsKey(id)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Exposicion e = exposiciones.get(id);

            //se muestran los datos propios de la exposición
            DatosExposicion.setText("Título: " + e.getTitulo() + "   |   Inicio: " + e.getfechaInicio() + "   |   Término: " + e.getfechaTermino());
            //se muestran las obras que contiene la exposición
            ArrayList<String> idObras = e.getIdsObras();
            String[] columnas = {"ID", "TITULO", "ARTISTA", "ESTADO", "AÑO"};
            DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
            for(int i = 0; i < idObras.size(); i++){
                Obra obra = obras.get(idObras.get(i));
                Object[] fila = {obra.getId(), obra.getTitulo(), (obra.getArtista()).getNombre(), obra.getEstado(), obra.getAnio()};
                modeloTabla.addRow(fila);
            }
            jTable1.setModel(modeloTabla);

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el ID de la Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BuscarExposicionPorIDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarExposicionPorID;
    private javax.swing.JLabel DatosExposicion;
    private javax.swing.JTextField IngresarIDExposicion;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
