/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
import java.util.*;
public class EliminarExposicionVentana extends javax.swing.JFrame {
    private HashMap<String, Exposicion> exposiciones;
    private HashMap<String, Obra> obras;
    /** Creates new form EliminarExposicionVentana */
    public EliminarExposicionVentana(HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.exposiciones = exposiciones;
        this.obras = obras;
    }

    private EliminarExposicionVentana() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //Se obtiene el texto de un campo, validando que no esté vacío
    private String obtenerTextoIngresado(javax.swing.JTextField campo) throws EmptyEntryException {
        String texto = campo.getText().trim();
        if(texto.isEmpty()){
            throw new EmptyEntryException();
        }
        return texto;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuExposiciones = new javax.swing.JButton();
        IngresarIDExposicion = new javax.swing.JTextField();
        EliminarExposicionBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuExposiciones.setText("Menu exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        IngresarIDExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarIDExposicionActionPerformed(evt);
            }
        });

        EliminarExposicionBoton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EliminarExposicionBoton.setForeground(new java.awt.Color(153, 0, 0));
        EliminarExposicionBoton.setText("Eliminar Exposicion");
        EliminarExposicionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarExposicionBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar ID de la exposicion que se desea eliminar:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(VolverMenuExposiciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(105, 105, 105)
                .add(EliminarExposicionBoton)
                .add(23, 23, 23))
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(EliminarExposicionBoton)
                    .add(VolverMenuExposiciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        MenuExposicionesVentana menu = new MenuExposicionesVentana(exposiciones, obras);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    private void IngresarIDExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarIDExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarIDExposicionActionPerformed

    private void EliminarExposicionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarExposicionBotonActionPerformed
        // TODO add your handling code here:
        try{
            String id = obtenerTextoIngresado(IngresarIDExposicion);

            //si la exposición no existe, se avisa y no se elimina nada
            if(!exposiciones.containsKey(id)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Exposicion e = exposiciones.get(id);

            //se pide confirmación porque la eliminación no se puede deshacer
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la exposición '" + e.getTitulo() + "'?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
            if(confirmacion != javax.swing.JOptionPane.YES_OPTION) return;

            exposiciones.remove(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Exposición eliminada correctamente", "ÉXITO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            IngresarIDExposicion.setText("");

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el ID de la Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarExposicionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EliminarExposicionVentana(new HashMap<String, Exposicion>(), new HashMap<String, Obra>()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarExposicionBoton;
    private javax.swing.JTextField IngresarIDExposicion;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
