
/**
 * @archivo: EliminarExposicionVentana.java
 * @Proyecto: Shaolin Art Manager 
 * @Descripción: Método para eliminar exposiciones por ventana
 * @author Antonia Avello
 * @Lenguaje: Java
*/

import java.util.*;
public class EliminarExposicionVentana extends javax.swing.JFrame {
    /** Creates new form EliminarExposicionVentana */

    //Se obtiene el texto de un campo, validando que no esté vacío
    private String obtenerTextoIngresado(javax.swing.JTextField campo) throws EmptyEntryException {
        String texto = campo.getText().trim();
        if(texto.isEmpty()){
            throw new EmptyEntryException();
        }
        return texto;
    }
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Exposicion> exposiciones;
    private final HashMap<String, Obra> obras;

    public EliminarExposicionVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.exposiciones = exposiciones;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuExposiciones = new javax.swing.JButton();
        IngresarIDExposicion = new javax.swing.JTextField();
        EliminarExposicionBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuExposiciones.setText("Menu exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        IngresarIDExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarIDExposicionActionPerformed(evt);
            }
        });

        EliminarExposicionBoton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EliminarExposicionBoton.setForeground(new java.awt.Color(153, 0, 0));
        EliminarExposicionBoton.setText("Eliminar Exposicion");
        EliminarExposicionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarExposicionBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar ID de la exposicion que se desea eliminar:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(VolverMenuExposiciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(105, 105, 105)
                .add(EliminarExposicionBoton)
                .add(23, 23, 23))
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(EliminarExposicionBoton)
                    .add(VolverMenuExposiciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    private void IngresarIDExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarIDExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarIDExposicionActionPerformed

    private void EliminarExposicionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarExposicionBotonActionPerformed
        // TODO add your handling code here:
        try{
            String id = obtenerTextoIngresado(IngresarIDExposicion);

            //si la exposición no existe, se avisa y no se elimina nada
            if(!exposiciones.containsKey(id)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Exposicion e = exposiciones.get(id);

            //se pide confirmación porque la eliminación no se puede deshacer
            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar la exposición '" + e.getTitulo() + "'?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
            if(confirmacion != javax.swing.JOptionPane.YES_OPTION) return;

            exposiciones.remove(id);
            javax.swing.JOptionPane.showMessageDialog(this, "Exposición eliminada correctamente", "ÉXITO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            IngresarIDExposicion.setText("");

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el ID de la Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarExposicionBotonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarExposicionBoton;
    private javax.swing.JTextField IngresarIDExposicion;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
