/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
import java.util.*;
import javax.swing.table.DefaultTableModel;


public class EliminarObraExposicionVentana extends javax.swing.JFrame {
    private HashMap<String, Exposicion> exposiciones;
    private HashMap<String, Obra> obras;
    /** Creates new form EliminarObraExposicion */
    public EliminarObraExposicionVentana(HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        this.exposiciones = exposiciones;
        this.obras = obras;

    }

    private EliminarObraExposicionVentana() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IngresarIDObra = new javax.swing.JTextField();
        EliminarObraBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VolverMenuExposiciones = new javax.swing.JButton();
        IngresarIDExposicion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IngresarIDObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarIDObraActionPerformed(evt);
            }
        });

        EliminarObraBoton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EliminarObraBoton.setForeground(new java.awt.Color(153, 0, 0));
        EliminarObraBoton.setText("Eliminar Obra");
        EliminarObraBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarObraBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID de la exposicion:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID de la obra:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        VolverMenuExposiciones.setText("Menu Exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(VolverMenuExposiciones))
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(EliminarObraBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarIDExposicion)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarIDObra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .add(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(VolverMenuExposiciones)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarIDExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(EliminarObraBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se obtiene el texto de un campo, validando que no esté vacío
    private String obtenerTextoIngresado(javax.swing.JTextField campo) throws EmptyEntryException {
        String texto = campo.getText().trim();
        if(texto.isEmpty()){
            throw new EmptyEntryException();
        }
        return texto;
    }
    
    
    private void IngresarIDObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarIDObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarIDObraActionPerformed

    private void EliminarObraBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarObraBotonActionPerformed
        try{
            String idExpo = obtenerTextoIngresado(IngresarIDExposicion);
            String idObra = obtenerTextoIngresado(IngresarIDObra);

            //se busca la exposición
            if(!exposiciones.containsKey(idExpo)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Exposicion e = exposiciones.get(idExpo);

            //se busca la obra
            if(!obras.containsKey(idObra)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Obra o = obras.get(idObra);

            //si la obra no estaba en la exposición, eliminarObra devuelve false
            if(!e.eliminarObra(o)){
                javax.swing.JOptionPane.showMessageDialog(this, "Esa obra no se encuentra en esta exposición", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Obra eliminada correctamente", "ÉXITO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //se actualiza la tabla con las obras de la exposición
            ArrayList<String> idObras = e.getIdsObras();
            String[] columnas = {"ID", "TITULO", "ARTISTA", "ESTADO", "AÑO"};
            DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
            for(int i = 0; i < idObras.size(); i++){
                Obra obra = obras.get(idObras.get(i));
                Object[] fila = {obra.getId(), obra.getTitulo(), (obra.getArtista()).getNombre(), obra.getEstado(), obra.getAnio()};
                modeloTabla.addRow(fila);
            }
            jTable1.setModel(modeloTabla);

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Debe ingresar el ID de la Exposición y el ID de la Obra", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EliminarObraBotonActionPerformed

    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        MenuExposicionesVentana menu = new MenuExposicionesVentana(exposiciones, obras);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarObraExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarObraExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarObraExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarObraExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EliminarObraExposicionVentana(new HashMap<String, Exposicion>(), new HashMap<String, Obra>()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarObraBoton;
    private javax.swing.JTextField IngresarIDExposicion;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
