/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Netaxion
 */

import java.time.*;
import java.time.format.DateTimeParseException;
import java.util.HashMap;
import javax.swing.JOptionPane;


public class MenuModificarExposicionesVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuModificarExposicionesVentana
     */
        private java.util.HashMap<String, Exposicion> exposiciones;
        private java.util.HashMap<String, Obra> obras ;
    private Exposicion exposicionActual;

    public MenuModificarExposicionesVentana(java.util.HashMap<String, Exposicion> exposiciones,java.util.HashMap<String, Obra> obras) {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.exposiciones = exposiciones;
        this.exposicionActual = null;
        this.obras=obras;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarIDButton = new javax.swing.JButton();
        IDExposicion = new javax.swing.JTextField();
        fechaInicioNueva = new javax.swing.JTextField();
        tituloNuevo = new javax.swing.JTextField();
        fechaTerminoNueva = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menú modificar exposiciones");

        buscarIDButton.setText("Buscar ID de exposición");
        buscarIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDButtonActionPerformed(evt);
            }
        });

        IDExposicion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IDExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDExposicionActionPerformed(evt);
            }
        });

        tituloNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloNuevoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìtulo de la exposición");

        jLabel3.setText("Fecha de inicio de la exposición");

        jLabel4.setText("Fecha de término de la exposición");

        volverButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        volverButton.setForeground(new java.awt.Color(153, 0, 0));
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        guardarButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarButton.setForeground(new java.awt.Color(0, 102, 102));
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(25, 25, 25))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarIDButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaInicioNueva)
                            .addComponent(tituloNuevo)
                            .addComponent(fechaTerminoNueva, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IDExposicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarIDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaInicioNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaTerminoNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDButtonActionPerformed
        // TODO add your handling code here:
        String id = IDExposicion.getText().trim();
        if (id.isEmpty()){  
            JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la Exposición.");
            return;
        }
        if (!exposiciones.containsKey(id)){ //si la exposicion no está en el mapa, se retorna y no se muestra nada
            JOptionPane.showMessageDialog(this, "La exposición no se encuentra en el sistema");
            exposicionActual = null;
            return;
        }
        //se guarda la exposición encontrada y se muestran sus datos actuales en los campos
        exposicionActual = exposiciones.get(id);
        tituloNuevo.setText(exposicionActual.getTitulo());
        fechaInicioNueva.setText(exposicionActual.getfechaInicio().toString());
        fechaTerminoNueva.setText(exposicionActual.getfechaTermino().toString());
        
    }//GEN-LAST:event_buscarIDButtonActionPerformed

    private void IDExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDExposicionActionPerformed

    private void tituloNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloNuevoActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed

        MenuExposicionesVentana v = new MenuExposicionesVentana(exposiciones, obras);
        v.setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_volverButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        
        if(exposicionActual == null){
            JOptionPane.showMessageDialog(this, "Primero debe buscar una Exposición por su ID.");
            return;
        }

        //se valida que el título no esté vacío
        String nuevoTitulo = tituloNuevo.getText().trim();
        if(nuevoTitulo.isEmpty()){
            JOptionPane.showMessageDialog(this, "El título no puede estar vacío.");
            return;
        }

        //se valida el formato de las fechas ingresadas
        LocalDate nuevaInicio;
        LocalDate nuevaTermino;
        try{
            nuevaInicio = LocalDate.parse(fechaInicioNueva.getText().trim());
            nuevaTermino = LocalDate.parse(fechaTerminoNueva.getText().trim());
        } catch (DateTimeParseException ex){
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use AAAA-MM-DD.");
            return;
        }

        //se validan ambas fechas juntas y se aplican los cambios
        if(!exposicionActual.cambiarFechas(nuevaInicio, nuevaTermino)){
            JOptionPane.showMessageDialog(this, "La exposición debe empezar antes de su término y durar como máximo un año.");
            return;
        }
        exposicionActual.cambiarTitulo(nuevoTitulo);

        JOptionPane.showMessageDialog(this, "La exposición fue modificada con éxito.");
    }//GEN-LAST:event_guardarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuModificarExposicionesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuModificarExposicionesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuModificarExposicionesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuModificarExposicionesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuExposicionesVentana(new HashMap<String, Exposicion>(), new HashMap<String, Obra>()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDExposicion;
    private javax.swing.JButton buscarIDButton;
    private javax.swing.JTextField fechaInicioNueva;
    private javax.swing.JTextField fechaTerminoNueva;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tituloNuevo;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
