
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicente
 */
public class MenuExposicionesVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuExposicionesVentana
     */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Exposicion> exposiciones;
    private final HashMap<String, Obra> obras;

    public MenuExposicionesVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.exposiciones = exposiciones;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        VolverMenuPrincipal = new javax.swing.JButton();
        EliminarExposicion = new javax.swing.JButton();
        RegistrarExposicion = new javax.swing.JButton();
        BuscarExposicion = new javax.swing.JButton();
        MenuExposiciones = new javax.swing.JLabel();
        MostrarExposciones = new javax.swing.JButton();
        ModificarExposicion = new javax.swing.JButton();
        AñadirObraAExposicion = new javax.swing.JButton();
        EliminarObraDeExposicion = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuPrincipal.setText("Volver Al Menu Principal");
        VolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrincipalActionPerformed(evt);
            }
        });

        EliminarExposicion.setText("Eliminar Exposicion");
        EliminarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarExposicionActionPerformed(evt);
            }
        });

        RegistrarExposicion.setText("Registrar Exposicion");
        RegistrarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarExposicionActionPerformed(evt);
            }
        });

        BuscarExposicion.setText("Buscar Exposicion");
        BuscarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarExposicionActionPerformed(evt);
            }
        });

        MenuExposiciones.setText("                 Menú Exposiciones");

        MostrarExposciones.setText("Mostrar Exposiciones");
        MostrarExposciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarExposcionesActionPerformed(evt);
            }
        });

        ModificarExposicion.setText("Modificar Exposicion");
        ModificarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarExposicionActionPerformed(evt);
            }
        });

        AñadirObraAExposicion.setText("Añadir Obra A Exposicion");
        AñadirObraAExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirObraAExposicionActionPerformed(evt);
            }
        });

        EliminarObraDeExposicion.setText("Eliminar Obra De Exposicion");
        EliminarObraDeExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarObraDeExposicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarExposciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñadirObraAExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarObraDeExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MostrarExposciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AñadirObraAExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarObraDeExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrincipalActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuPrincipalActionPerformed

    private void EliminarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarExposicionActionPerformed
        // TODO add your handling code here:
        //para no eliminar si no hay exposiciones registradas
        if(exposiciones.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "No hay exposiciones registradas");
            return;
        }
        EliminarExposicionVentana v = new EliminarExposicionVentana(this, exposiciones, obras);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarExposicionActionPerformed
       
    private void RegistrarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarExposicionActionPerformed
        // TODO add your handling code here:
        RegistrarExposicionVentana v = new RegistrarExposicionVentana(this, exposiciones, obras);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarExposicionActionPerformed

    private void BuscarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarExposicionActionPerformed
        // TODO add your handling code here:
        BuscarExposicionVentana v = new BuscarExposicionVentana(this, exposiciones, obras);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BuscarExposicionActionPerformed

    private void MostrarExposcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarExposcionesActionPerformed
        MostrarExposicionesVentana v = new MostrarExposicionesVentana(this, exposiciones, obras);
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarExposcionesActionPerformed

    private void ModificarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarExposicionActionPerformed
        MenuModificarExposicionesVentana v1 = new MenuModificarExposicionesVentana(this, exposiciones, obras);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModificarExposicionActionPerformed

    private void AñadirObraAExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirObraAExposicionActionPerformed
        // TODO add your handling code here:
        AñadirObraExposicionVentana v1 = new AñadirObraExposicionVentana(this, exposiciones, obras);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AñadirObraAExposicionActionPerformed

    private void EliminarObraDeExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarObraDeExposicionActionPerformed
        // TODO add your handling code here:
        EliminarObraExposicionVentana v1 = new EliminarObraExposicionVentana(this, exposiciones, obras);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarObraDeExposicionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirObraAExposicion;
    private javax.swing.JButton BuscarExposicion;
    private javax.swing.JButton EliminarExposicion;
    private javax.swing.JButton EliminarObraDeExposicion;
    private javax.swing.JLabel MenuExposiciones;
    private javax.swing.JButton ModificarExposicion;
    private javax.swing.JButton MostrarExposciones;
    private javax.swing.JButton RegistrarExposicion;
    private javax.swing.JButton VolverMenuPrincipal;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
