/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vicente
 */
public class MenuExposicionesVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuExposicionesVentana
     */
    
    private java.util.HashMap<String, Exposicion> exposiciones;
    private java.util.HashMap<String, Obra> obras;
    
    public MenuExposicionesVentana() {
        initComponents();
    }
    public MenuExposicionesVentana(java.util.HashMap<String, Exposicion> exposiciones, java.util.HashMap<String, Obra> obras) {
        initComponents();
        this.exposiciones = exposiciones;
        this.obras = obras;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuPrincipal = new javax.swing.JButton();
        EliminarExposicion = new javax.swing.JButton();
        RegistrarExposicion = new javax.swing.JButton();
        BuscarExposicion = new javax.swing.JButton();
        MenuExposiciones = new javax.swing.JLabel();
        MostrarExposciones = new javax.swing.JButton();
        ModificarExposicion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuPrincipal.setText("Volver Al Menu Principal");
        VolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrincipalActionPerformed(evt);
            }
        });

        EliminarExposicion.setText("Eliminar Exposicion");
        EliminarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarExposicionActionPerformed(evt);
            }
        });

        RegistrarExposicion.setText("Registrar Exposicion");
        RegistrarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarExposicionActionPerformed(evt);
            }
        });

        BuscarExposicion.setText("Buscar Exposicion");
        BuscarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarExposicionActionPerformed(evt);
            }
        });

        MenuExposiciones.setText("                 Menú Exposiciones");

        MostrarExposciones.setText("Mostrar Exposiciones");
        MostrarExposciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarExposcionesActionPerformed(evt);
            }
        });

        ModificarExposicion.setText("Modificar Exposicion");
        ModificarExposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarExposicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarExposciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarExposicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(MenuExposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MostrarExposciones, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegistrarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(EliminarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarExposicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VolverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrincipalActionPerformed
        MenuPrincipalVentana v1 = new MenuPrincipalVentana();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuPrincipalActionPerformed

    private void EliminarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarExposicionActionPerformed
       
    private void RegistrarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarExposicionActionPerformed

    private void BuscarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarExposicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarExposicionActionPerformed

    private void MostrarExposcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarExposcionesActionPerformed
        
    }//GEN-LAST:event_MostrarExposcionesActionPerformed

    private void ModificarExposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarExposicionActionPerformed
        MenuModificarExposicionesVentana v1 = new MenuModificarExposicionesVentana(exposiciones,obras);
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModificarExposicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuExposicionesVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuExposicionesVentana().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarExposicion;
    private javax.swing.JButton EliminarExposicion;
    private javax.swing.JLabel MenuExposiciones;
    private javax.swing.JButton ModificarExposicion;
    private javax.swing.JButton MostrarExposciones;
    private javax.swing.JButton RegistrarExposicion;
    private javax.swing.JButton VolverMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
