/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
import java.util.*;
import java.time.*;
import java.time.format.DateTimeParseException;

public class RegistrarExposicionVentana extends javax.swing.JFrame {
    private HashMap<String, Exposicion> exposiciones;
    private HashMap<String, Obra> obras;

    public RegistrarExposicionVentana(HashMap<String, Exposicion> exposiciones, HashMap<String, Obra> obras) {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.exposiciones = exposiciones;
        this.obras = obras;
    }

    private RegistrarExposicionVentana() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverMenuExposiciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TituloObra = new javax.swing.JLabel();
        IngresarTituloExposicion = new javax.swing.JTextField();
        NombreArtistaObra = new javax.swing.JLabel();
        IngresarFechaInicio = new javax.swing.JTextField();
        AnioCreacionObra = new javax.swing.JLabel();
        IngresarFechaTermino = new javax.swing.JTextField();
        RegistrarExposicionBoton = new javax.swing.JButton();
        AnioCreacionObra1 = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverMenuExposiciones.setText("Menu Exposiciones");
        VolverMenuExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuExposicionesActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrar Obra");

        TituloObra.setText("Título De La Exposicion:");

        NombreArtistaObra.setText("Fecha De Inicio:");

        AnioCreacionObra.setText("Fecha De Termino:");

        RegistrarExposicionBoton.setText("Registrar Exposicion");
        RegistrarExposicionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarExposicionBotonActionPerformed(evt);
            }
        });

        AnioCreacionObra1.setText("Ingresar ID De La Primera Obra:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(RegistrarExposicionBoton)
                .add(140, 140, 140))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(VolverMenuExposiciones))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jLabel1)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, TituloObra)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, NombreArtistaObra)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(0, 11, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra1)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AnioCreacionObra))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(IngresarIDObra)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarFechaTermino)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarTituloExposicion)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, IngresarFechaInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 258, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(VolverMenuExposiciones)
                    .add(jLabel1))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TituloObra)
                    .add(IngresarTituloExposicion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarFechaInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(NombreArtistaObra))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarFechaTermino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AnioCreacionObra))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(IngresarIDObra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(AnioCreacionObra1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegistrarExposicionBoton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se obtiene el texto de un campo, validando que no esté vacío
    private String obtenerTextoIngresado(javax.swing.JTextField campo) throws EmptyEntryException {
        String texto =campo.getText().trim();
        if(texto.isEmpty()){
            throw new EmptyEntryException();
        }
        return texto;
    }
    
    private void VolverMenuExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuExposicionesActionPerformed
        MenuExposicionesVentana menu = new MenuExposicionesVentana(exposiciones, obras);
        menu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_VolverMenuExposicionesActionPerformed

    private void RegistrarExposicionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarExposicionBotonActionPerformed
        try{
            //se obtienen los datos validando que ningún campo esté vacío con el método ya creado
            String titulo = obtenerTextoIngresado(IngresarTituloExposicion);
            String textoInicio = obtenerTextoIngresado(IngresarFechaInicio);
            String textoTermino = obtenerTextoIngresado(IngresarFechaTermino);
            String idObra = obtenerTextoIngresado(IngresarIDObra);

            //se valida el formato de las fechas ingresadas (si esto falla, se atrapa el error)
            LocalDate fInicio = LocalDate.parse(textoInicio);
            LocalDate fTermino = LocalDate.parse(textoTermino);

            //se valida que el término sea posterior al inicio y que no supere un año
            if(!Exposicion.rangoDeFechasValido(fInicio, fTermino)){
                javax.swing.JOptionPane.showMessageDialog(this, "La exposición debe empezar antes de su término y durar como máximo un año", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            //se busca la obra con la que se inicia la exposición
            if(!obras.containsKey(idObra)){
                javax.swing.JOptionPane.showMessageDialog(this, "No existe esa obra", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Obra o = obras.get(idObra);

            //se verifica el estado de la obra
            String estado = o.getEstado();
            if(!estado.equalsIgnoreCase("DISPONIBLE")){
                javax.swing.JOptionPane.showMessageDialog(this, "La obra '" + o.getTitulo() + "' no está disponible para exponerse (estado: " + estado + ")", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                
                return;
            }

            //se genera el ID y se registra la exposición
            String id = IDManager.generarID(titulo);
            Exposicion e = new Exposicion(id, titulo, fInicio, fTermino, o);
            exposiciones.put(id, e);
            javax.swing.JOptionPane.showMessageDialog(this, "Exposición registrada correctamente (ID: " + id + ")", "ÉXITO!", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            //se limpian los campos para poder registrar otra
            IngresarTituloExposicion.setText("");
            IngresarFechaInicio.setText("");
            IngresarFechaTermino.setText("");
            IngresarIDObra.setText("");

        } catch (EmptyEntryException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No puede dejar campos vacíos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Formato de fecha inválido. Use AAAA-MM-DD", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegistrarExposicionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarExposicionVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrarExposicionVentana(new HashMap<String, Exposicion>(), new HashMap<String, Obra>()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnioCreacionObra;
    private javax.swing.JLabel AnioCreacionObra1;
    private javax.swing.JTextField IngresarFechaInicio;
    private javax.swing.JTextField IngresarFechaTermino;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JTextField IngresarTituloExposicion;
    private javax.swing.JLabel NombreArtistaObra;
    private javax.swing.JButton RegistrarExposicionBoton;
    private javax.swing.JLabel TituloObra;
    private javax.swing.JButton VolverMenuExposiciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
