
/**
 * @archivo: CerrarSubastaActiva.java
 * @Proyecto: Shaolin Art Manager 
 * @Descripción: Método para cerrar la subasta que está activa actualmente por ventana
 * @author Vicente Gamboa
 * @Lenguaje: Java
*/

import java.util.*;

public class CerrarSubastaActiva extends javax.swing.JFrame {

    /** Creates new form CerrarSubastaActiva */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Cliente> clientes;
    private final ArrayList<Subasta> subastas;

    public CerrarSubastaActiva(javax.swing.JFrame ventanaAnterior, HashMap<String, Cliente> clientes, ArrayList<Subasta> subastas) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.clientes = clientes;
        this.subastas = subastas;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
        actualizarInfoSubasta();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InfoSubasta = new javax.swing.JLabel();
        CerrarSubastaBoton = new javax.swing.JButton();
        VolverMenuSubastas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cerrar Subasta Activa");

        InfoSubasta.setText("No hay ninguna subasta activa en este momento.");

        CerrarSubastaBoton.setText("Cerrar Subasta");
        CerrarSubastaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSubastaBotonActionPerformed(evt);
            }
        });

        VolverMenuSubastas.setText("Menu Subastas");
        VolverMenuSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuSubastasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(InfoSubasta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CerrarSubastaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(VolverMenuSubastas)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(InfoSubasta)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CerrarSubastaBoton)
                    .addComponent(VolverMenuSubastas))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarSubastaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSubastaBotonActionPerformed
        //verificar que haya una subasta activa
        if (MenuPrincipal.subastaActiva == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna subasta activa para cerrar.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // se guarda la obra antes de cerrar, para poder liberarla si es que no hubo ofertas
        Obra obraSubastada = MenuPrincipal.subastaActiva.getObra();

        boolean exito = MenuPrincipal.subastaActiva.cerrarSubasta(clientes);

        if (exito) { //Si se logró cerrar la subasta con éxito (con al menos una oferta registrada)
            subastas.add(MenuPrincipal.subastaActiva); //se añade la subasta al ArrayList de subastas cerradas
            String rutGanador = (MenuPrincipal.subastaActiva.getCliente()).getRut();
            int precioFinal = MenuPrincipal.subastaActiva.getPrecio();
            javax.swing.JOptionPane.showMessageDialog(this, "Subasta cerrada exitosamente. Ganador RUT: " + rutGanador + " por $" + precioFinal, "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            // si no hubo ofertas, la obra vuelve a estar disponible
            if (obraSubastada != null && obraSubastada.getEstado().equalsIgnoreCase("SUBASTANDO")) {
                obraSubastada.setEstado("Disponible");
            }
            javax.swing.JOptionPane.showMessageDialog(this, "La subasta se cerró sin ninguna oferta. La obra '" + obraSubastada.getTitulo() + "' vuelve a estar DISPONIBLE.", "Aviso",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        // Reiniciamos la variable de subastaActiva
        MenuPrincipal.subastaActiva = null;
        actualizarInfoSubasta();
    }//GEN-LAST:event_CerrarSubastaBotonActionPerformed

    private void VolverMenuSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuSubastasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuSubastasActionPerformed

    //muestra en la ventana los datos de la subasta activa (o un aviso si no hay ninguna)
    private void actualizarInfoSubasta(){
        if (MenuPrincipal.subastaActiva == null){
            InfoSubasta.setText("No hay ninguna subasta activa en este momento.");
            return;
        }
        Obra o = MenuPrincipal.subastaActiva.getObra();
        Oferta mejor = MenuPrincipal.subastaActiva.getMejorOferta();
        String texto = "Obra: " + o.getTitulo() + " | Precio inicial: $" + MenuPrincipal.subastaActiva.getPrecioInicial();
        if (mejor == null){
            texto = texto + " | Sin ofertas";
        }
        else{
            texto = texto + " | Mejor oferta: $" + mejor.getOferta() + " (RUT: " + mejor.getRut() + ")";
        }
        InfoSubasta.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel InfoSubasta;
    private javax.swing.JButton CerrarSubastaBoton;
    private javax.swing.JButton VolverMenuSubastas;
    // End of variables declaration//GEN-END:variables

}
