/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;
import java.time.*;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Vicente Gamboa
 */
public class IniciarNuevaSubastaVentana extends javax.swing.JFrame {

    /** Creates new form IniciarNuevaSubastaVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Obra> obras;

    public IniciarNuevaSubastaVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Obra> obras) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.obras = obras;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IngresarPrecioInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IngresarFechaSubasta = new javax.swing.JTextField();
        IniciarSubastaBoton = new javax.swing.JButton();
        VolverMenuSubastas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Iniciar Nueva Subasta");

        jLabel1.setText("ID Obra:");

        jLabel2.setText("Precio Inicial:");

        jLabel3.setText("Fecha (AAAA-MM-DD):");

        IniciarSubastaBoton.setText("Iniciar Subasta");
        IniciarSubastaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSubastaBotonActionPerformed(evt);
            }
        });

        VolverMenuSubastas.setText("Menu Subastas");
        VolverMenuSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuSubastasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarPrecioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarFechaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IniciarSubastaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(VolverMenuSubastas)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IngresarPrecioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IngresarFechaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IniciarSubastaBoton)
                    .addComponent(VolverMenuSubastas))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSubastaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSubastaBotonActionPerformed
        //Si hay una subastaActiva, no se abre una nueva hasta que la activa se cierre
        if (MenuPrincipal.subastaActiva != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya hay una subasta en curso.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Se verifica que la obra esté registrada
        String idObra = IngresarIDObra.getText().trim();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(idObra);

        // se verifica el estado de la obra -------------
        String estado = o.getEstado();
        if(!estado.equalsIgnoreCase("DISPONIBLE")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra '" + o.getTitulo() + "' no está disponible para ser subastada (estado: " + estado + ")", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //se valida el precio inicial (entero positivo)
        int precioInicial = -1;
        try {
            precioInicial = Integer.parseInt(IngresarPrecioInicial.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese solo números enteros válidos. No se aceptan letras ni símbolos.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (precioInicial < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio no puede ser negativo.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //se valida la fecha de la subasta
        LocalDate fecha = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada = IngresarFechaSubasta.getText().trim();
        try {
            fecha = LocalDate.parse(entrada);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida respetando el formato AAAA-MM-DD", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // INICIALIZAR VARIABLE GLOBAL DE MENU
        MenuPrincipal.subastaActiva = new Subasta(o, precioInicial, fecha);

        // la obra queda bloqueada mientras dure la subasta, así no se puede
        // vender, prestar ni añadir a una exposición
        o.setEstado("SUBASTANDO");

        javax.swing.JOptionPane.showMessageDialog(this, "Subasta iniciada con éxito. La obra '" + o.getTitulo() + "' queda en estado SUBASTANDO.", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_IniciarSubastaBotonActionPerformed

    private void VolverMenuSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuSubastasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuSubastasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField IngresarPrecioInicial;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField IngresarFechaSubasta;
    private javax.swing.JButton IniciarSubastaBoton;
    private javax.swing.JButton VolverMenuSubastas;
    // End of variables declaration//GEN-END:variables

}
