/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;
import java.time.*;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Alejandro
 */
public class IniciarNuevaSubastaVentana extends javax.swing.JFrame {

    /** Creates new form IniciarNuevaSubastaVentana */
    private ArrayList<Venta> ventas;
    private HashMap<String, Obra> obras;
    private HashMap<String, Cliente> clientes;
    private ArrayList<Subasta> subastas;

    public IniciarNuevaSubastaVentana() {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
    }
    public IniciarNuevaSubastaVentana(ArrayList<Venta> ventas, HashMap<String, Obra> obras, HashMap<String, Cliente> clientes, ArrayList<Subasta> subastas) {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.ventas = ventas;
        this.obras = obras;
        this.clientes = clientes;
        this.subastas = subastas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarIDObra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IngresarPrecioInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IngresarFechaSubasta = new javax.swing.JTextField();
        IniciarSubastaBoton = new javax.swing.JButton();
        VolverMenuSubastas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Iniciar Nueva Subasta");

        jLabel1.setText("ID Obra:");

        jLabel2.setText("Precio Inicial:");

        jLabel3.setText("Fecha (AAAA-MM-DD):");

        IniciarSubastaBoton.setText("Iniciar Subasta");
        IniciarSubastaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSubastaBotonActionPerformed(evt);
            }
        });

        VolverMenuSubastas.setText("Menu Subastas");
        VolverMenuSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuSubastasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarPrecioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarFechaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IniciarSubastaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(VolverMenuSubastas)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IngresarIDObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IngresarPrecioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(IngresarFechaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IniciarSubastaBoton)
                    .addComponent(VolverMenuSubastas))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSubastaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSubastaBotonActionPerformed
        //Si hay una subastaActiva, no se abre una nueva hasta que la activa se cierre
        if (MenuPrincipal.subastaActiva != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ya hay una subasta en curso.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Se verifica que la obra esté registrada
        String idObra = IngresarIDObra.getText().trim();
        if(!obras.containsKey(idObra)){
            javax.swing.JOptionPane.showMessageDialog(this, "No existe esa Obra", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Obra o = obras.get(idObra);

        // se verifica el estado de la obra -------------
        String estado = o.getEstado();
        if(!estado.equalsIgnoreCase("DISPONIBLE")){
            javax.swing.JOptionPane.showMessageDialog(this, "La obra '" + o.getTitulo() + "' no está disponible para ser subastada (estado: " + estado + ")", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //se valida el precio inicial (entero positivo)
        int precioInicial = -1;
        try {
            precioInicial = Integer.parseInt(IngresarPrecioInicial.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese solo números enteros válidos. No se aceptan letras ni símbolos.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (precioInicial < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio no puede ser negativo.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //se valida la fecha de la subasta
        LocalDate fecha = null; //Se inicia la fecha en NULL, para cambiarla solo si se ingresa una fecha válida en el formato válido
        String entrada = IngresarFechaSubasta.getText().trim();
        try {
            fecha = LocalDate.parse(entrada);
        } catch(DateTimeParseException | NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida respetando el formato AAAA-MM-DD", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // INICIALIZAR VARIABLE GLOBAL DE MENU
        MenuPrincipal.subastaActiva = new Subasta(o, precioInicial, fecha);

        // la obra queda bloqueada mientras dure la subasta, así no se puede
        // vender, prestar ni añadir a una exposición
        o.setEstado("SUBASTANDO");

        javax.swing.JOptionPane.showMessageDialog(this, "Subasta iniciada con éxito. La obra '" + o.getTitulo() + "' queda en estado SUBASTANDO.", "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_IniciarSubastaBotonActionPerformed

    private void VolverMenuSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuSubastasActionPerformed
        MenuSubastasVentana menu = new MenuSubastasVentana(ventas, obras, clientes, subastas);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuSubastasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevaSubastaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevaSubastaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevaSubastaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarNuevaSubastaVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarNuevaSubastaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField IngresarIDObra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField IngresarPrecioInicial;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField IngresarFechaSubasta;
    private javax.swing.JButton IniciarSubastaBoton;
    private javax.swing.JButton VolverMenuSubastas;
    // End of variables declaration//GEN-END:variables

}
