/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;

/**
 *
 * @author Vicente Gamboa
 */
public class MenuSubastasVentana extends javax.swing.JFrame {

    /** Creates new form MenuSubastasVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta
    private final HashMap<String, Obra> obras;
    private final HashMap<String, Cliente> clientes;
    private final ArrayList<Subasta> subastas;

    public MenuSubastasVentana(javax.swing.JFrame ventanaAnterior, HashMap<String, Obra> obras, HashMap<String, Cliente> clientes, ArrayList<Subasta> subastas) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.obras = obras;
        this.clientes = clientes;
        this.subastas = subastas;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSubastas = new javax.swing.JLabel();
        MostrarSubastasCerradas = new javax.swing.JButton();
        IniciarNuevaSubasta = new javax.swing.JButton();
        RegistrarNuevaOferta = new javax.swing.JButton();
        CerrarSubasta = new javax.swing.JButton();
        VolverMenuVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuSubastas.setText("                   Menú Subastas");

        MostrarSubastasCerradas.setText("Mostrar Subastas Cerradas");
        MostrarSubastasCerradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarSubastasCerradasActionPerformed(evt);
            }
        });

        IniciarNuevaSubasta.setText("Iniciar Nueva Subasta");
        IniciarNuevaSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarNuevaSubastaActionPerformed(evt);
            }
        });

        RegistrarNuevaOferta.setText("Registrar Nueva Oferta");
        RegistrarNuevaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNuevaOfertaActionPerformed(evt);
            }
        });

        CerrarSubasta.setText("Cerrar Subasta Activa");
        CerrarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSubastaActionPerformed(evt);
            }
        });

        VolverMenuVentas.setText("Volver Al Menu Ventas");
        VolverMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarSubastasCerradas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciarNuevaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarNuevaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(MenuSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MostrarSubastasCerradas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(IniciarNuevaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(RegistrarNuevaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(CerrarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(VolverMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarSubastasCerradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarSubastasCerradasActionPerformed
        MostrarSubastasCerradasVentana mostrar = new MostrarSubastasCerradasVentana(this, subastas);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarSubastasCerradasActionPerformed

    private void IniciarNuevaSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarNuevaSubastaActionPerformed
        IniciarNuevaSubastaVentana iniciar = new IniciarNuevaSubastaVentana(this, obras);
        iniciar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IniciarNuevaSubastaActionPerformed

    private void RegistrarNuevaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNuevaOfertaActionPerformed
        RegistrarNuevaOfertaSubastaVentana ofertar = new RegistrarNuevaOfertaSubastaVentana(this);
        ofertar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarNuevaOfertaActionPerformed

    private void CerrarSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSubastaActionPerformed
        CerrarSubastaActiva cerrar = new CerrarSubastaActiva(this, clientes, subastas);
        cerrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSubastaActionPerformed

    private void VolverMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuVentasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuVentasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuSubastas;
    private javax.swing.JButton MostrarSubastasCerradas;
    private javax.swing.JButton IniciarNuevaSubasta;
    private javax.swing.JButton RegistrarNuevaOferta;
    private javax.swing.JButton CerrarSubasta;
    private javax.swing.JButton VolverMenuVentas;
    // End of variables declaration//GEN-END:variables

}
