/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.*;

/**
 *
 * @author Alejandro
 */
public class MenuSubastasVentana extends javax.swing.JFrame {

    /** Creates new form MenuSubastasVentana */
    private ArrayList<Venta> ventas;
    private HashMap<String, Obra> obras;
    private HashMap<String, Cliente> clientes;
    private ArrayList<Subasta> subastas;

    public MenuSubastasVentana() {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
    }
    public MenuSubastasVentana(ArrayList<Venta> ventas, HashMap<String, Obra> obras, HashMap<String, Cliente> clientes, ArrayList<Subasta> subastas) {
        initComponents();
        Datos.guardarAlCerrar(this); //se guardan los archivos al cerrar la ventana
        this.ventas = ventas;
        this.obras = obras;
        this.clientes = clientes;
        this.subastas = subastas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSubastas = new javax.swing.JLabel();
        MostrarSubastasCerradas = new javax.swing.JButton();
        IniciarNuevaSubasta = new javax.swing.JButton();
        RegistrarNuevaOferta = new javax.swing.JButton();
        CerrarSubasta = new javax.swing.JButton();
        VolverMenuVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuSubastas.setText("                   Menú Subastas");

        MostrarSubastasCerradas.setText("Mostrar Subastas Cerradas");
        MostrarSubastasCerradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarSubastasCerradasActionPerformed(evt);
            }
        });

        IniciarNuevaSubasta.setText("Iniciar Nueva Subasta");
        IniciarNuevaSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarNuevaSubastaActionPerformed(evt);
            }
        });

        RegistrarNuevaOferta.setText("Registrar Nueva Oferta");
        RegistrarNuevaOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNuevaOfertaActionPerformed(evt);
            }
        });

        CerrarSubasta.setText("Cerrar Subasta Activa");
        CerrarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSubastaActionPerformed(evt);
            }
        });

        VolverMenuVentas.setText("Volver Al Menu Ventas");
        VolverMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarSubastasCerradas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciarNuevaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarNuevaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CerrarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(MenuSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MostrarSubastasCerradas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(IniciarNuevaSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(RegistrarNuevaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(CerrarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(VolverMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarSubastasCerradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarSubastasCerradasActionPerformed
        MostrarSubastasCerradasVentana mostrar = new MostrarSubastasCerradasVentana(ventas, obras, clientes, subastas);
        mostrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MostrarSubastasCerradasActionPerformed

    private void IniciarNuevaSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarNuevaSubastaActionPerformed
        IniciarNuevaSubastaVentana iniciar = new IniciarNuevaSubastaVentana(ventas, obras, clientes, subastas);
        iniciar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IniciarNuevaSubastaActionPerformed

    private void RegistrarNuevaOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNuevaOfertaActionPerformed
        RegistrarNuevaOfertaSubastaVentana ofertar = new RegistrarNuevaOfertaSubastaVentana(ventas, obras, clientes, subastas);
        ofertar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarNuevaOfertaActionPerformed

    private void CerrarSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSubastaActionPerformed
        CerrarSubastaActiva cerrar = new CerrarSubastaActiva(ventas, obras, clientes, subastas);
        cerrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSubastaActionPerformed

    private void VolverMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuVentasActionPerformed
        MenuVentasVentana menu = new MenuVentasVentana(ventas, obras, clientes, subastas);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverMenuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSubastasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSubastasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSubastasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSubastasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSubastasVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuSubastas;
    private javax.swing.JButton MostrarSubastasCerradas;
    private javax.swing.JButton IniciarNuevaSubasta;
    private javax.swing.JButton RegistrarNuevaOferta;
    private javax.swing.JButton CerrarSubasta;
    private javax.swing.JButton VolverMenuVentas;
    // End of variables declaration//GEN-END:variables

}
