
/**
 * @archivo: RegistrarNuevaOfertaSubastaVentana.java
 * @Proyecto: Shaolin Art Manager 
 * @Descripción: Método para registrar una nueva oferta para la subasta activa por ventana
 * @author Vicente Gamboa
 * @Lenguaje: Java
*/

import java.util.*;

public class RegistrarNuevaOfertaSubastaVentana extends javax.swing.JFrame {

    /** Creates new form RegistrarNuevaOfertaSubastaVentana */
    private final javax.swing.JFrame ventanaAnterior; //ventana desde la que se abrió esta

    public RegistrarNuevaOfertaSubastaVentana(javax.swing.JFrame ventanaAnterior) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        //si se cierra esta ventana con la X, se le avisa a la ventana anterior para que también se cierre,
        //así el aviso llega hasta el menú principal, que es el que guarda los archivos
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                ventanaAnterior.dispatchEvent(new java.awt.event.WindowEvent(ventanaAnterior, java.awt.event.WindowEvent.WINDOW_CLOSING));
            }
        });
        actualizarInfoSubasta();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        InfoSubasta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IngresarRutCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        IngresarMontoOferta = new javax.swing.JTextField();
        RegistrarOfertaBoton = new javax.swing.JButton();
        VolverMenuSubastas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Registrar Nueva Oferta");

        InfoSubasta.setText("No hay ninguna subasta activa en este momento.");

        jLabel1.setText("RUT Cliente:");

        jLabel2.setText("Monto Oferta:");

        RegistrarOfertaBoton.setText("Registrar Oferta");
        RegistrarOfertaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarOfertaBotonActionPerformed(evt);
            }
        });

        VolverMenuSubastas.setText("Menu Subastas");
        VolverMenuSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuSubastasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(InfoSubasta)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarMontoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistrarOfertaBoton)
                        .addGap(18, 18, 18)
                        .addComponent(VolverMenuSubastas)))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(InfoSubasta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IngresarRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IngresarMontoOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarOfertaBoton)
                    .addComponent(VolverMenuSubastas))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarOfertaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarOfertaBotonActionPerformed
        //Si no hay una subasta activa, no se puede registrar una oferta
        if (MenuPrincipal.subastaActiva == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna subasta activa en este momento.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String rutOfertador = IngresarRutCliente.getText().trim();
        if (rutOfertador.isEmpty() || rutOfertador.length() < 8 || rutOfertador.length() > 9) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un RUT válido", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        //--------------------------------------------------------------- se hacen las validaciones correspondientes para añadir la oferta
        int monto = -1;
        try {
            monto = Integer.parseInt(IngresarMontoOferta.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese solo números enteros válidos. No se aceptan letras ni símbolos.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (monto < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto no puede ser negativo.", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Oferta ofertaActual = MenuPrincipal.subastaActiva.getMejorOferta(); //se obtiene la mejor oferta
        int precioInicial = MenuPrincipal.subastaActiva.getPrecioInicial(); // se obtiene el precio inicial
        //si es la primera oferta
        if (ofertaActual == null) {
            if (monto < precioInicial) { //Se verifica que la oferta sea mayor al precio inicial
                javax.swing.JOptionPane.showMessageDialog(this, "La primera oferta debe ser mayor o igual al precio inicial ($" + precioInicial + ").", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        // Si ya existen ofertas
        else {
            if (monto <= ofertaActual.getOferta()) { //se valida que se ingrese una oferta mayor a la mejor oferta actual
                javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un monto mayor a la oferta actual ($" + ofertaActual.getOferta() + ")", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // si pasa las validaciones, la oferta es valida y podemos añadirla
        MenuPrincipal.subastaActiva.ofertar(monto, rutOfertador);
        javax.swing.JOptionPane.showMessageDialog(this, "Nueva mayor oferta: $" + monto + " por Cliente RUT: " + rutOfertador, "ÉXITO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        actualizarInfoSubasta();
    }//GEN-LAST:event_RegistrarOfertaBotonActionPerformed

    private void VolverMenuSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuSubastasActionPerformed
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMenuSubastasActionPerformed

    //muestra en la ventana los datos de la subasta activa (o un aviso si no hay ninguna)
    private void actualizarInfoSubasta(){
        if (MenuPrincipal.subastaActiva == null){
            InfoSubasta.setText("No hay ninguna subasta activa en este momento.");
            return;
        }
        Obra o = MenuPrincipal.subastaActiva.getObra();
        Oferta mejor = MenuPrincipal.subastaActiva.getMejorOferta();
        String texto = "Obra: " + o.getTitulo() + " | Precio inicial: $" + MenuPrincipal.subastaActiva.getPrecioInicial();
        if (mejor == null){
            texto = texto + " | Sin ofertas";
        }
        else{
            texto = texto + " | Mejor oferta: $" + mejor.getOferta() + " (RUT: " + mejor.getRut() + ")";
        }
        InfoSubasta.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel InfoSubasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField IngresarRutCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField IngresarMontoOferta;
    private javax.swing.JButton RegistrarOfertaBoton;
    private javax.swing.JButton VolverMenuSubastas;
    // End of variables declaration//GEN-END:variables

}
